// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

import { IEnvironment } from './ienvironment';

export const environment: IEnvironment = {
  environmentName: 'production',
  production: true,
  version: '0.0.0',
  serverUrl: 'https://api.grandmercado.com/api/v1',
  authServiceURL: 'https://auth.grandmercado.com/api/v1',
  defaultLanguage: 'es-ES',
  supportedLanguages: ['en-US', 'es-ES'],
  appRelease: 'APP_RELEASE_PLACEHOLDER',
  assetsPrefix: 'grandmercado-b2b-web',
  googleTagManagerId: 'GTM-KH8KF3X',
  sentryDSN:
    'https://67e52cc1d3bc416484f89e9d9852bce7@o311836.ingest.sentry.io/4504249755238400',
  appID: 'd16e05e9-80c4-4b6c-a08a-7c6296baa82f',
};
