// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

import { IEnvironment } from './ienvironment';

export const environment: IEnvironment = {
  environmentName: 'stage',
  production: true,
  version: 0 + '-stage',
  serverUrl: 'https://test.grandmercado.com/api/v1',
  authServiceURL: 'https://auth-test.grandmercado.com/api/v1',
  defaultLanguage: 'es-ES',
  supportedLanguages: ['en-US', 'es-ES'],
  appRelease: 'APP_RELEASE_PLACEHOLDER',
  assetsPrefix: 'grandmercado-b2b-web',
  googleTagManagerId: 'GTM-MVMMJ2R',
  sentryDSN:
    'https://67e52cc1d3bc416484f89e9d9852bce7@o311836.ingest.sentry.io/4504249755238400',
  appID: '55738d28-4ffb-4b95-aa5e-f75662d27233',
};
